name: Transfer Artifact

on:
  workflow_dispatch:

env:
  VIZIAPPS_REPO: ViziApps/wmrt-appservice_artifacts
  PERSONAL_REPO: Umapoornima/Test_wmrt-appservice_artifacts
  FILE_NAME: appservice_artifacts.zip

jobs:
  transfer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Personal Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Clone from ViziApps repo using VIZIAPPS_TOKEN
        run: |
          git clone https://${{ secrets.VIZIAPPS_TOKEN }}@github.com/${{ env.VIZIAPPS_REPO }} repo-a
          cp repo-a/${{ env.FILE_NAME }} .

      - name: Configure Git User
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "action@github.com"

      - name: Push artifact to Personal repo with workflow file preserved
        run: |
          git lfs track "${{ env.FILE_NAME }}"
          git add -f .gitattributes
          git add "${{ env.FILE_NAME }}"
          
          if git diff --cached --quiet; then
            echo "Nothing to commit"
          else
            git commit -m "Imported ZIP from ViziApps using Git LFS on $(date '+%Y-%m-%d %H:%M:%S')"
            git push origin main
          fi
